"""Adds many to many relationship

Revision ID: 9b3b7951c0fd
Revises: 51d3916754e2
Create Date: 2024-07-04 16:54:33.699635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3b7951c0fd'
down_revision = '51d3916754e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_meetings',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_meetings_employee_id_employees')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_employee_meetings_meeting_id_meetings')),
    sa.PrimaryKeyConstraint('employee_id', 'meeting_id')
    )
    op.drop_table('employees_meetings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_meetings',
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_employees_meetings_employee_id_employees'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name='fk_employees_meetings_meeting_id_meetings'),
    sa.PrimaryKeyConstraint('employee_id', 'meeting_id')
    )
    op.drop_table('employee_meetings')
    # ### end Alembic commands ###
